config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
 resources :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # view all the pages
  def index
    @pages = Page.all
    # renders index.html.erb
  end
  
  # showing a single page
  def show
    # Page.find(1), below is a placeholder for id
    @page = Page.find(params[:id])
    # renders show.html.erb
  end
  
  # displays the form to create the new page
  def new
    @page = Page.new
    # renders new.html.erb
  end

# post request to create the page

def create
  @page = Page.new(pages_params)

  if @page.save
    redirect_to pages_path
  else
    render :new
  end

end

# edit form
  def edit
    @page = Page.find(params[:id])
  end

  # update the page
def update
  @page = Page.find(params[:id])

  if @page.update(pages_params)
    redirect_to pages_path
  else
    # takes them back to edit if they can't or don't edit
    render :edit
  end
end

def destroy
  Page.find(params[:id]).destroy
  redirect_to pages_path
end

#  anything inside the private won't get 
  private
  # This is creating an object of key value pairs, {title: 'adsd', author: 'asds'}
  def pages_params
    params.require(:page).permit(:title, :author, :body)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Blog Pages</h1>
<% @pages.each do |page| %>
  <%= link_to 'Show Page', page_path(page) %>
  <%= link_to 'Edit Page', edit_page_path(page) %>
  <%= link_to 'Delete Page', page, method: :delete %>
<% end %>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>Create a Page</h1>
<%= form_for @page do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<%= @page.author %>
<p><%= @page.body %></p>

<%# navigational links %>

<%= link_to 'Back', pages_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>